#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. $DIR/powermenu-options

MENU="$(rofi -sep "|" -dmenu -i -p "$MENU_TITLE" -location 2 -yoffset 100 -width 15 -lines 4 <<< "$LOCK_ICON Lock|$LOGOUT_ICON Logout|$REBOOT_ICON Reboot|$SHUTDOWN_ICON Shutdown")"
case "$MENU" in
    *Lock) $HOME/.config/locker/lock.sh ;;
    *Logout) i3-msg exit ;;
    *Reboot) systemctl reboot ;;
    *Shutdown) systemctl -i poweroff
esac
