#! perl

use v5.20;
use common::sense;

our @resources = (
      qw(
          background foreground
          cursorColor cursorColor2
          borderColor
      ),
      map { "color$_" } 0..15
    );

sub on_start {
    for (@resources) {
        say "$_: " . $TERM->x_resource($_);
    }
    exit;
}
